In [1]:
import os,sys
sys.path.append("../../")
from analysis_common import *
from root_common import *
from analysis_helpers import *

Welcome to JupyROOT 6.26/00


In [2]:
%jsroot on

In [3]:
dir_files_GEM21_11b = "/Users/wketchum/Data/LDMX/eN_Ti_GENIE_v3_2_0/ldmx_eTi_4GeV_GEM21_11b_00"
dir_files_G18_02a = "/Users/wketchum/Data/LDMX/eN_Ti_GENIE_v3_2_0/ldmx_eTi_4GeV_G18_02a_00"

gst_files_GEM21_11b = glob.glob(f"{dir_files_GEM21_11b}/*gst.root")
gst_files_G18_02a = glob.glob(f"{dir_files_G18_02a}/*gst.root")

gst_chain_GEM21_11b = create_gst_chain(gst_files_GEM21_11b,verbose=True)
gst_chain_G18_02a = create_gst_chain(gst_files_G18_02a,verbose=True)

df_gst_GEM21_11b_all = ROOT.RDataFrame(gst_chain_GEM21_11b)
df_gst_G18_02a_all = ROOT.RDataFrame(gst_chain_G18_02a)

Created gst chain from 100 files with 10000000 total events.
Created gst chain from 100 files with 10000000 total events.


In [4]:
gst_df = pd.DataFrame()

In [8]:
for batch in uproot.iterate(["/Users/wketchum/Data/LDMX/eN_Ti_GENIE_v3_2_0/ldmx_eTi_4GeV_GEM21_11b_00/*gst.root:gst"],["pdgf","Ef","pxf","pyf","pzf"],library='pd'):
    gst_df = pd.concat([gst_df,batch])

In [11]:
gst_df["pf"] = np.sqrt(gst_df["pxf"]*gst_df["pxf"]+gst_df["pyf"]*gst_df["pyf"]+gst_df["pzf"]*gst_df["pzf"])

In [17]:
gst_df["mass2f"] = (gst_df["Ef"]*gst_df["Ef"])-(gst_df["pf"]*gst_df["pf"])

In [19]:
gst_df["mass2f"] = np.where(gst_df["mass2f"] > 0, gst_df["mass2f"], 0)

In [20]:
gst_df["massf"] = np.sqrt(gst_df["mass2f"])

In [32]:
gst_df["kef"] = gst_df["Ef"]-gst_df["massf"]

In [33]:
gst_df[["Ef","kef"]]

Ef       kef
entry   subentry                    
0       0         1.374766  0.436494
        1         1.964012  1.824441
        2         1.035363  0.095797
        3         0.987936  0.048371
        4         0.954587  0.015021
...                    ...       ...
9999996 4         1.059787  0.121515
9999997 0         0.962188  0.023916
9999998 0         0.982826  0.043261
        1         0.987873  0.048308
9999999 0         1.099357  0.159791

[48162278 rows x 2 columns]

In [38]:
gst_df_proton = gst_df.loc[gst_df["pdgf"]==2212]
gst_df_piplus = gst_df.loc[gst_df["pdgf"]==211]
gst_df_piminus = gst_df.loc[gst_df["pdgf"]==-211]

In [40]:
gst_df_piminus[:1000000]

pdgf        Ef       pxf       pyf       pzf        pf  \
entry   subentry                                                           
8       1         -211  0.586735 -0.259186 -0.055483  0.504502  0.569893   
        4         -211  0.338873 -0.010896 -0.244111  0.188802  0.308797   
27      1         -211  0.205486  0.108532 -0.081344 -0.065944  0.150814   
37      1         -211  0.686413  0.551244  0.271569  0.272146  0.672074   
51      2         -211  0.591126 -0.013489 -0.018292  0.573963  0.574413   
...                ...       ...       ...       ...       ...       ...   
7175174 0         -211  0.367980  0.334839 -0.052547 -0.032419  0.340484   
7175175 2         -211  0.193282 -0.052906  0.082252  0.091180  0.133709   
7175177 1         -211  0.344225 -0.174244 -0.040906  0.258799  0.314660   
        4         -211  0.336015  0.065645 -0.151527  0.257210  0.305658   
7175178 0         -211  1.393609 -0.328278 -0.796400  1.086575  1.386602   

                    massf   mass2f       kef  
entry   subentry                              
8       1         0.13957  0.01948  0.447165  
        4         0.13957  0.01948  0.199303  
27      1         0.13957  0.01948  0.065916  
37      1         0.13957  0.01948  0.546843  
51      2         0.13957  0.01948  0.451556  
...                   ...      ...       ...  
7175174 0         0.13957  0.01948  0.228409  
7175175 2         0.13957  0.01948  0.053712  
7175177 1         0.13957  0.01948  0.204655  
        4         0.13957  0.01948  0.196445  
7175178 0         0.13957  0.01948  1.254039  

[1000000 rows x 9 columns]

In [37]:
gst_df_proton[:1000000][["pdgf","massf","Ef","pxf","pyf","pzf","pf"]].to_csv("hadron_vars_proton_1e6.txt",index=None,sep=" ")

In [41]:
gst_df_piplus[:1000000][["pdgf","massf","Ef","pxf","pyf","pzf","pf"]].to_csv("hadron_vars_piplus_1e6.txt",index=None,sep=" ")
gst_df_piminus[:1000000][["pdgf","massf","Ef","pxf","pyf","pzf","pf"]].to_csv("hadron_vars_piminus_1e6.txt",index=None,sep=" ")

In [31]:
gst_file = uproot.open("%s:gst"%gst_files_GEM21_11b[0])

In [35]:
gst_file.arrays(["pdgf","Ef","pxf","pyf","pzf"],library='pd')

pdgf        Ef       pxf       pyf       pzf
entry subentry                                              
0     0         2212  1.374766 -0.291521 -0.251298  0.928166
      1          211  1.964012  0.084785  0.004602  1.957205
      2         2112  1.035363  0.059675 -0.013148 -0.430649
      3         2112  0.987936 -0.052816 -0.297455 -0.044333
      4         2112  0.954587 -0.063629  0.145491 -0.056889
...              ...       ...       ...       ...       ...
99996 2         2112  1.009408 -0.272455 -0.096558  0.229271
99997 0         2112  1.171604 -0.550442 -0.247511  0.354436
      1         2212  1.289313  0.785944  0.299267  0.273323
99998 0         2112  1.060698  0.390122 -0.290628 -0.075078
99999 0         2212  0.956286  0.142985  0.112931  0.030516

[483251 rows x 5 columns]

In [25]:
df_gst_GEM21_11b_all = df_gst_GEM21_11b_all.Range(100)

In [26]:
df_gst_GEM21_11b_all = define_df_gst_lep_vars(df_gst_GEM21_11b_all)
df_gst_GEM21_11b_all = define_df_gst_hadron_vars(df_gst_GEM21_11b_all)
df_gst_GEM21_11b_all = define_df_gst_hadrons_by_pdg(df_gst_GEM21_11b_all)

In [27]:
cols = df_gst_GEM21_11b_all.AsNumpy(["nf","pdgf","massf","vtxx","vtxy","vtxz","pxf","pyf","pzf","Ef","kef"])

In [28]:
cols["nf"]

ndarray([ 9,  3,  7,  3,  6,  1,  1,  7,  5, 12,  6, 10,  1,  1,  5,  1,
          1,  3,  6,  1,  1,  1,  9, 25,  5,  1,  5, 13,  1,  1,  1,  8,
          2,  3,  2,  2,  6,  2,  5,  5,  1,  4,  1,  1,  3,  1,  1,  2,
          1,  6,  1, 16,  1,  4,  1,  1,  3,  1, 19,  2, 26, 10, 16,  2,
          4,  1,  6, 27, 14, 11,  2,  4,  1, 13,  1,  9, 16,  2,  2,  2,
         14,  2,  3,  1,  6,  6,  6,  5,  5,  3, 10,  2,  1,  3,  6, 22,
          1,  3,  2,  1], dtype=int32)

In [29]:
for cname in ["pdgf","massf","pxf","pyf","pzf","Ef","kef"]:
    cols[cname] = [ np.asarray(c) for c in cols[cname] ]

In [30]:
cols["pdgf"]

[array([282560344,     32724,         1,     32724,         0,         0,
                0,     32724,         0], dtype=int32),
 array([ -8,  -1, 111], dtype=int32),
 array([-2147483648,          -1,   536870912,           0,  1018882656,
              32724,  1018882656], dtype=int32),
 array([2212, 2112,   -8], dtype=int32),
 array([       2112,        2212,          -8,          -1, -2147483648,
                 -1], dtype=int32),
 array([0], dtype=int32),
 array([-8], dtype=int32),
 array([1018880672,      32724, 1018880672,      32724,          0,
                 0, -424914112], dtype=int32),
 array([ 211, -211,  111, 2212, -211], dtype=int32),
 array([1018880992,      32724, 1018880992,      32724, 1018880992,
             32724, 1018880992,      32724,          0,          0,
        -424914112,      32766], dtype=int32),
 array([2212, 2112, 2112, 2212, 2212, 2212], dtype=int32),
 array([-2147483648,          -1,   536870912,           0,  1018882656,
              32724,  10

In [ ]:
branchList = ROOT.vector('string')()
for branchName in ["nf","pdgf","massf","vtxx","vtxy","vtxz","pxf","pyf","pzf","Ef","kef"]:
    branchList.push_back(branchName)

In [ ]:
df_gst_GEM21_11b_all.Snapshot("gst","/Users/wketchum/Data/LDMX/eN_Ti_GENIE_v3_2_0/gst_GEM21_11b_hadrons.root",branchList)